FROM ubuntu:18.04

RUN apt-get update -y

RUN apt-get install -y build-essential bash-completion man  manpages-posix 
# Installing python
RUN apt-get install -y python3 python3-pip virtualenv python3-numpy python3-dev python3-wheel
# Install vim, optional, but just if needed
RUN apt-get install -y vim git wget unzip sudo
# Install several needed tools
RUN apt-get install -y patch diffutils libtinfo-dev autoconf graphviz yapf3 python3-yapf

# Install protobuf for serialization of the models
RUN apt install -y protobuf-compiler libprotobuf-dev


# Install clang-9
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
RUN apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
RUN apt-get update && apt install -y clang-9 clang-tidy-9 clang-format-9


# # Install CMAKE
# RUN mkdir -p /root/deps/cmake
# RUN cd /root/deps
# RUN wget https://github.com/Kitware/CMake/releases/download/v3.16.1/cmake-3.16.1-Linux-x86_64.sh 
# RUN bash cmake-3.16.1-Linux-x86_64.sh --skip-license --prefix=/root/deps/cmake
# RUN ln -s /root/deps/cmake/bin/cmake /bin/cmake
# RUN ln -s /root/deps/cmake/bin/ccmake /bin/ccmake
# # Installing git

# # Install Clang 6.0
# RUN apt-get install clang

# # Install onnx
# RUN pip3 install onnx==1.5.0
# # Install ngraph-core
# RUN pip3 install ngraph-core
# # Install ngraph bridge to ONNX
# RUN pip3 install ngraph-onnx
# # Install plaidml for acceleration
# RUN pip3 install plaidml
# # Install tensorflow
# RUN pip3 install -U tensorflow==1.14.0
# # Install ngraph-tensorflow-bridge
# RUN pip3 install ngraph-tensorflow-bridge
# # Install scikit-learn
# RUN pip3 install scikit-learn
# # Install onnx runtime
# RUN pip3 install onnxruntime
# # Install ONNX converter for Keras
# RUN pip3 install keras2onnx



# Colored terminal
# RUN useradd -s /bin/bash -d /home/jocabrer -m -G sudo jocabrer
RUN echo "PS1='\[\033[01;31m\](docker) \[\e[01;36m\]\u\[\e[01;37m\]@\[\e[01;33m\]\H\[\e[01;37m\]:\[\e[01;32m\]\w\[\e[01;37m\]\$\[\033[0;37m\] '" >> /root/.bashrc
RUN echo "alias python=python3" >> /root/.bashrc
RUN echo "alias pip=pip3" >> /root/.bashrc


WORKDIR /root
CMD ['bash']
